/**:
  ros__parameters:
    input_frame: "base_link"
    output_frame: "base_link"
    min_x: -100.0
    max_x: 100.0
    min_y: -100.0
    max_y: 100.0
    min_z: -30.0
    max_z: 50.0
    negative: False
