# see AvoidanceParameters description in avoidance_module_data.hpp for description.
/**:
  ros__parameters:
    avoidance:
      resample_interval_for_planning: 0.3
      resample_interval_for_output: 4.0
      detection_area_right_expand_dist: 1.0
      detection_area_left_expand_dist: 1.0

      enable_avoidance_over_same_direction: true
      enable_avoidance_over_opposite_direction: false

      threshold_distance_object_is_on_center: 1.0 # [m]
      threshold_speed_object_is_stopped: 0.5      # [m/s]
      object_check_forward_distance: 50.0        # [m]
      object_check_backward_distance: 2.0         # [m]
      lateral_collision_margin: 0.25               # [m]
      lateral_collision_safety_buffer: 0.30        # [m]

      prepare_time: 2.0                           # [s]
      min_prepare_distance: 1.0                   # [m]
      min_avoidance_distance: 10.0                # [m]

      min_nominal_avoidance_speed: 1.5  # [m/s]
      min_sharp_avoidance_speed: 1.0    # [m/s]

      road_shoulder_safety_margin: 0.01 # [m]

      max_right_shift_length: 2.0 # [m]
      max_left_shift_length: 2.0 # [m]

      nominal_lateral_jerk: 0.1   # [m/s3]
      max_lateral_jerk: 0.4       # [m/s3]

      object_last_seen_threshold: 2.0   # [s]

      # For prevention of large acceleration while avoidance
      min_avoidance_speed_for_acc_prevention: 3.0  # [m/s]
      max_avoidance_acceleration: 0.5  # [m/ss]

      # for debug
      publish_debug_marker: true
      print_debug_info: false

      # not enabled yet
      longitudinal_collision_margin_min_distance: 0.0          # [m]
      longitudinal_collision_margin_time: 0.0

      # avoidance is performed for the object type with true
      target_object:
        car: true
        truck: true
        bus: true
        trailer: true
        unknown: true
        bicycle: false
        motorcycle: false
        pedestrian: false

      # ---------- advanced parameters ----------
      avoidance_execution_lateral_threshold: 0.499

      # static expansion of drivable_area
      static_expand_drivable_area: true
      static_right_bound_offset: 2.8
      static_left_bound_offset: 2.8
