/**:
  ros__parameters:
    max_vibration_pitch: 0.01745329251   # -0.5 ~ 0.5 deg
    max_vibration_yaw: 0.01745329251     # -0.5 ~ 0.5 deg
    max_vibration_height: 0.20          # -0.05 ~ 0.05 m
    max_vibration_width: 0.20           # -0.05 ~ 0.05 m
    max_vibration_depth: 0.05             # -0.05 ~ 0.05 m

    # Scale value  = 1.0 + (scale_factor / scale_start_distance)
    scale_start_distance: 30.0
    scale_factor: 10.0

    # overwrite traffic light
