/**:
  ros__parameters:
    max_vibration_pitch: 0.01745329251   # -0.5 ~ 0.5 deg
    max_vibration_yaw: 0.01745329251     # -0.5 ~ 0.5 deg
    max_vibration_height: 0.10          # -0.05 ~ 0.05 m
    max_vibration_width: 0.10           # -0.05 ~ 0.05 m
    max_vibration_depth: 0.10             # -0.05 ~ 0.05 m
    tl_offset_x: -0.1
    tl_offset_y: 0.1
    tl_offset_z: 0.0
    tl_offset_r_deg: 0.0
    tl_offset_p_deg: 0.0
    tl_offset_y_deg: 0.0
