/**:
  ros__parameters:
    hdd_reader_port: 7635
    num_disks: 2
    disks: # Until multi type lists are allowed, name N the disks as disk0...disk{N-1}
      disk0:
        name: /dev/sdb2  #2TB
        temp_warn: 55.0
        temp_error: 70.0
        power_on_hours_warn: 3000000
        total_data_written_warn: 31250   # =1TB (1unit=32MB)
        total_data_written_safety_factor: 0.05
        free_warn: 5120 # MB(8hour)
        free_error: 100 # MB(last 1 minute)
      disk1:
        name: /dev/sda  #8TB
        temp_warn: 55.0
        temp_error: 70.0
        power_on_hours_warn: 3000000
        total_data_written_warn: 218750   # =7TB (1unit=32MB)
        total_data_written_safety_factor: 0.05
        free_warn: 5120 # MB(8hour)
        free_error: 100 # MB(last 1 minute)
